# Site settings
title: Clever Blog Title
email: campfish91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is just a simple blog on data visualization, with a clever title.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonahwilliams.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  jonahwilliams

# Build settings
markdown: kramdown
